### ISSUE TITLE
Bad access when calling a function on returned userdata

### ISSUE THREAD

**Issue by notlion** [Rapptz/sol#35]
Hi! I'm trying to bind a class that returns instances of it's own type. Here's a simplified example:

``` cpp
struct Vec {
  float x, y, z;
  Vec(float x, float y, float z) : x{x}, y{y}, z{z} {}
  float length() {
    return sqrtf(x*x + y*y + z*z);
  }
  Vec normalized() {
    float invS = 1 / length();
    return {x * invS, y * invS, z * invS};
  }
};

sol::state lua;
lua.open_libraries(sol::lib::base);

sol::constructors<sol::types<float, float, float>> ctor;
sol::userdata<Vec> udata("Vec", ctor,
  "normalized", &Vec::normalized,
  "length",     &Vec::length);

lua.set_userdata(udata);
```

This script works:

``` cpp
lua.script("v = Vec.new(1, 2, 3)\n"
           "print(v:length())");
// --> 3.7416574954987
```

But this one fails:

``` cpp
lua.script("v = Vec.new(1, 2, 3)\n"
           "print(v:normalized():length())");
// --> EXC_BAD_ACCESS
```

Is it possible to do this with sol, or am I missing something?

**Comment by dgdev1024** [comment]
Main.cpp

``` c++
#include <sol.hpp>
#include <cmath>

struct Vec {
    float x, y, z;
    Vec(float x, float y, float z) : x{x}, y{y}, z{z} {}
    float length() {
        return sqrtf(x*x + y*y + z*z);
    }
    Vec normalized() {
        float invS = 1 / length();
        return {x * invS, y * invS, z * invS};
    }
};

int main()
{
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    sol::constructors<sol::types<float, float, float>> ctor;
    sol::userdata<Vec> udata("Vec", ctor,
      "normalized", &Vec::normalized,
      "length",     &Vec::length);

    lua.set_userdata(udata);

    lua.open_file("Test.lua");

    return 0;
}
```

Test.lua

``` lua
v = Vec.new(1, 2, 3)
n = v:normalized()

print(n:length())
```

Running the code, 'print(n:length())' yields some weird results.
Five different executions of the program yield the following:
0
inf
0
854380
1.2764733714477e-11

Is there anything I'm missing/doing wrong? Thank you.

**Comment by Rapptz** [comment]
I only get 0, which is still incorrect of course. It seems that the test case for this didn't actually verify the result but rather just tested if it didn't raise an error. I recommend opening a new issue.

**Comment by Rapptz** [comment]
This actually seems to be "fixed" in the `develop` branch sort of. It returns `0.99999994039536` instead of `1` but I suppose it's "close enough"? There must be some sort of issue going on with the accuracy but it's better than zero.

**Comment by dgdev1024** [comment]
I guess the only thing I'm missing here is the concept of git branches. I had no idea there was a develop branch. Anyway, looks like my issue's been resolved. Thank you so!

As for the inaccuracy, I believe that is natural with Lua's C API. I had the same issue with a different non-c++11 Lua-wrapping API (namely, https://bitbucket.org/alexames/luawrapper/src).

A safe workaround would probably be to round it maybe to six decimal places...
