### ISSUE TITLE
sol::table::iterator & friends

### ISSUE THREAD

**Issue by ThePhD** [Rapptz/sol#59]
libjansson offers a c-style "any" iterator where you can fix values from the type [like so](https://jansson.readthedocs.org/en/latest/apiref.html#c.json_object_key_to_iter). A similar API (that's less wonky since we're in C++) could probably be created and allowed for with table's `begin()` and `end()` syntax, using `sol::object` for values and perhaps a new `sol::key` type (since keys can only be integers or strings in `lua`).

I'd be interested in doing this for version 2.0 later on!

**Comment by Rapptz** [comment]
I've thought about this before but it didn't seem feasible to do. I could re-consider the issue but I don't think much has changed to make this feasible.

**Comment by ThePhD** [comment]
Shit-tier [iterator version](https://gist.github.com/ThePhD/4d517f922edad68a98fb). I would say this could be made easier but shitty C++ for loops can't handle multiple different types, and there's no "single iterator" type, so. Screw iterators.
