### ISSUE TITLE
Registering a function inside a table

### ISSUE THREAD

**Issue by iganinja** [Rapptz/sol#69]
Hi

Is there a way to register a function from C++ so it is contained in a table? So I can call from Lua this way:

```
local v = MyStuff.doSomething(...)
```

Thanks

**Comment by ThePhD** [comment]
Yes. Make the table in lua or in C++, get the table, and then call `mytable.set_function( ... );`, like you would with anything. E.g...

```
sol::state lua;
sol::table mystuff = lua.create_table("MyStuff");
mystuff.set_function( "doSomething", &doSomething );
```

If the table already exists, you can just do `sol::table mystuff = lua.get<sol::table>( "MyStuff" );` instead of creating the table. Shorter syntax is `sol::table mystuff = lua["MyStuff"];`, which I believe SHOULD work (there might be an exception for tables in the current `main`/`develop` branches, which could be changed on my `develop` branch).

**Comment by iganinja** [comment]
Thanks for the answer. I get a compilation error in create_table() call, which I think is the same error as in #68. I will try the patch of this issue to see if everything works (I am using the develop branch, btw)

**Comment by ThePhD** [comment]
No problem. If you run into further build issues just look at the mega pull-request references in #68, that is, everything in #62 (or just at ThePhD/sol, branch develop). Should all be resolved there.

**Comment by iganinja** [comment]
I used #68 patch and it worked correctly. Anyway thanks for the #62 and your develop branch tips, I will keep them in mind.

**Comment by iganinja** [comment]
Hi again

I replaced my old sol files with the ones from ThePhD/sol, branch develop and I get compiler erros. The first one is this:

\sol\function_types.hpp:171: error: expected primary-expression before 'decltype'
         decltype(auto) r = stack::call(L, 0, types<return_type>(), ta, fx);
         ^

Any clue about that?

Thanks

**Comment by ThePhD** [comment]
You're most likely compiling with -std=c++11. That's a C++14 feature. I have to backpeddle and fix that, but it'll require some extra lines of code...

**Comment by iganinja** [comment]
Thanks for the fast answer.

I was compiling with -std=c++1y flag. I switched to -std=c++14 and now I have other errors. First one:

sol\function.hpp:211: error: 'call' was not declared in this scope
     -> decltype(call<Ret...>(std::forward<Args>(args)...)) {
                 ^

I am using mingw 4.9.1. Do you think it's due to this version not implementing all the C++14 standard?

**Comment by ThePhD** [comment]
You should be okay with that. I'm using MinGW 5.x and I had some of the same errors. It was peculiar; it seems g++ didn't have quite the same binding rules for r-value refs to l-value refs in their compiler as VC++, so I had to change how I used `std::declval<T>()` to make it behave better with g++.

I dare say you should be all set, with the new changes I just pushed.

**Comment by iganinja** [comment]
I used your latest version and it compiles ok, thank you very much! :) Just in case you want to fix it, it has a warning of no return value in function.hpp in operator = at line 70.

By the way, capturing a variable in a lambda which returns a tuple should be possible, shouldn't it? I am having compilation errors even with your branch:

```
int a = 0;
luaVM1.set_function("test", [a]()
{
    return std::make_tuple(10, 10.0f);
});
```

**Comment by ThePhD** [comment]
What are the errors? That looks like it should work just fine.

**Comment by iganinja** [comment]
I have this one with the code above:

```
sol\function_types.hpp:347: error: no matching function for call to 'call(lua_State*&, int, sol::types<int,     float>&, sol::types<>&, main()::<lambda()>&)'
         return_type r = stack::call(L, 0, tr, ta, fx);
                                            ^
```

**Comment by iganinja** [comment]
Excuse me ThePhD, your last changes made my code to compile but I missed the linker messages: I am having multiple definition errors like this one:

```
sol\stack.hpp:578: error: multiple definition of `sol::stack::remove(lua_State*, int, int)'
```

This happens without the tuple returning stuff, they are not related (should I create another issue for that tuple returning error?)

**Comment by ThePhD** [comment]
Woops. I forgot an `inline`. Fixing that and the other error now.

**Comment by ThePhD** [comment]
Alright, pushed. I will also add a test case for that so I don't forget to do that again.

**Comment by iganinja** [comment]
It seems sol::function::default_handler scaped your raid ^^U

```
error: multiple definition of `sol::function::default_handler'
```

BTW tupple stuff compiles now ;)

**Comment by ThePhD** [comment]
Hey @iganinja , just checking in to make sure everything's set? If so, closing the issue might help!

**Comment by iganinja** [comment]
Sorry ThePhD, I forgot informing about my experiments: everything compiles and works except that redefinition of default_handler. I created a function which returns a static variable and it compiles. Otherwise as said before everything is OK, thanks :)

**Comment by ThePhD** [comment]
I fixed the default_handler in the latest push with exactly that kind of fix, so I think everything's set.

**Comment by iganinja** [comment]
I downloaded your last version and now I have an error in stack.hpp:

```
line 344: error: void value not ignored as it ought to be
    return ref.push();
                    ^
```

By the way, develop branch has no sol.hpp file

**Comment by ThePhD** [comment]
I... think something's wrong with what branch you're pulling...? `main`, `develop`, and `ThePhD/develop` all have `sol.hpp`, and that error isn't present either. Either way, tests are compiling and the like. Make sure everything you have is up to date and you're in the right directory.

**Comment by iganinja** [comment]
Indeed ThePhD, I messed something around there. Now it compiles and works correctly so I close the issue. Sorry for the inconvenience.
