### ISSUE TITLE
`sol::table`: Checking for existance of key

### ISSUE THREAD

**Issue by Nava2** [Rapptz/sol#73]
Is there a means for checking for an existence of a key within a `sol::table`? 

Additionally, when using `sol::table::operator[]`, it returns a `sol::proxy`. However, this type has no means of checking the type of the underlying value. 

Something like this might be neat: 

``` c++
sol::table tbl; // assume it's initialized
if (auto prox = tbl["my_key"])
{
  // use prox
}
else
{
  // prox doesn't actually exist
}
```

A method such as `exists()` would be useful, too. I took this syntax suggestion from boost's `optional` type.

**Comment by ThePhD** [comment]
``` cpp
sol::object x = tbl["my_key"];
if ( x != sol::nil ) {
// good to go
}
else {
// not good to go
}
```

**Comment by ThePhD** [comment]
I don't think we have an explicit `exists` function, though. It would be nice to add, you are right. I'll keep it in mind as I keep developing.

**Comment by Nava2** [comment]
That's great! I knew I must be missing something. You already have an issue open for documentation, I guess this is a great case and point for it. 

For `exists()`, it would be nice. Frankly, inlining that check seems like a pretty quick and dirty solution.

**Comment by Nava2** [comment]
Correction, `objects.hpp`:

``` c++
bool valid() const {
        return !this->is<nil_t>();
    }
```

**Comment by ThePhD** [comment]
I'll be sure to add it to the documentation. Right now I'm finishing the featureset necessary to get sol v2.0 off the ground (work is being done [here](https://github.com/ThePhD/sol2)).

**Comment by Nava2** [comment]
Closing this as I've found the use cases. :+1:
