### ISSUE TITLE
Template member

### ISSUE THREAD

**Issue by PhilCK** [Rapptz/sol#76]
Is it possible to bind a template member function?

I'm trying to bind a varient class.

I've tried

``` cpp
  m_lua.new_usertype<Test::Param>(
    "Param",
    "get_bool", &Test::Param::get<bool>
  );
```

That produces error, `expecting 3 arguments`

and (although I didn't have hope in this one.)

``` cpp
  m_lua.new_usertype<Test::Param>(
    "Param",
    "get_bool", static_cast<bool (Test::Param::*) ()>( &Test::Param::get<bool> )
  );
```

**Comment by victorlevasseur** [comment]
This should work, but you should take a look at a far newer (and maintained) version of Sol : https://github.com/ThePhD/sol2

**Comment by PhilCK** [comment]
oops too many tabs posted in wrong repo.
